Update plot.zh_cn.md
ProjectHDS/Herodotus pull request #6
Opened 2021-04-16 12:22 UTC by ikexing-cn

尝试按照苟佬的文风和我自己的理解改了一下句子的连贯感，
改了一下时间不对等的问题。

2021-04-16 12:22 UTC, ikexing-cn commented
@RisingInIris2017

2021-04-16 12:32 UTC, GBLodb approved these changes
![image](https://user-images.githubusercontent.com/59724679/115024561-d81d3880-9ef2-11eb-8d20-f2bc224381c8.png)

2021-04-16 12:56 UTC, RisingInIris2017 requested changes
此次Review中我没有Comment的修改，都是我认为可以改的。
我针对修改当中我有疑义的部分做了说明。这些地方值得在进一步讨论的基础上作后续的修改。

2021-04-16 12:56 UTC, RisingInIris2017 commented on docs/plots/plot.zh_cn.md
“与此同时”可以有，但是删去开头的这个“但”字不妥。
理由是“我脑海中的声音”是正在操纵主角的记忆那个超维计算机，和主角实际上是分开的两个实体。
主角有意不理会超维计算机的操纵，超维计算机也不顾主角的想法，不停地操纵主角的记忆。
这两者形成了某种“对抗”，这个“但”字表达的强烈转折正是在隐含这个层面的意思。
所以开头这个“但”字不能删去。

2021-04-16 12:56 UTC, RisingInIris2017 commented on docs/plots/plot.zh_cn.md
“内涵”和“外延”是“概念”的两个处于平等地位的属性，一个概念拥有属于它的内涵和外延。
所以“和”可以不必改为“及其”，因为这两者的地位是平等的。

2021-04-16 12:56 UTC, RisingInIris2017 commented on docs/plots/plot.zh_cn.md
> +对我来说也曾那么的真实，但现在我只感到它们的陌生和不定否决的荒诞。
这一句不必改。
“对我来说曾经那么真实”的原因是超维计算机在17行主角睁开眼睛之前，把主角的记忆删除了，所以主角醒来时感到的是这些东西曾经是真实的。但是由于没删干净或者其他与咖喱的设定相契合的设定，主角仍然隐隐约约记得一些东西，但又觉得它们不真实，所以“陌生而荒诞”。这里我们就把“真实”“陌生”“荒诞”三个形容词摆在这里，简洁地营造出一种对立的感觉就行了，在“荒诞”前面补词可能会导致句子变得冗长，那种对立冲突的感觉就被淡化消解了，这样不合适。
所以我认为这一句不改比较妥当。

2021-04-16 12:56 UTC, RisingInIris2017 commented on docs/plots/plot.zh_cn.md
> +真是疯狂的真实，真实的疯狂。我自言自语道。
这个“得”是我故意选择的。“真实得疯狂”，这里的“疯狂”是修饰“真实”的程度。
展开写就是“太真实了，以至于疯狂”。
咖喱在英文版剧情里面的英文翻译能传达出这种意思，
*It was crazy reality, so real it was crazy.*

2021-04-16 12:56 UTC, RisingInIris2017 commented on docs/plots/plot.zh_cn.md
如果要这样改，那就把上一句的句号改成逗号，把“再一次”这一句接到上一句的后面。

2021-04-16 12:56 UTC, RisingInIris2017 commented on docs/plots/plot.zh_cn.md
这一句话不管怎么改，一定要和第21行保持精确的完全一样。
这样才能故意地引起读者对前文的回忆，形成前后呼应。
换句话说，这句话的文字不管改成什么样子，一定要把21行也改成这个样子。

2021-04-16 12:56 UTC, RisingInIris2017 commented on docs/plots/plot.zh_cn.md
“哲学家的三个终极问题”是个梗，改了玩梗的味道会轻一点，没准也好。

2021-04-16 13:00 UTC, ikexing-cn commented on docs/plots/plot.zh_cn.md
说实话这一块我有歧义，因为你完全的保持原样会导致信息错乱，
我个人的认为，前文的回忆并不适用于序章的简洁，我能理解为苟佬你想保持住两边的交融度，寻求共同解，但实际上我感觉这会导致处于一种疑惑状态，
那就是，清醒，还是迷糊，亦或到是如何。所以这是我想寻改的一个思路。

2021-04-16 13:01 UTC, ikexing-cn commented on docs/plots/plot.zh_cn.md
那这个属于我阅读范畴的边缘了，我以为是苟佬你想表达一种轻快随意感，那这边既然是梗我觉得可保原意

2021-04-16 13:02 UTC, ikexing-cn commented on docs/plots/plot.zh_cn.md
实际上我有想过这一块，但苟佬我看大多的结束都是以句号结尾，并且第一人称「我」作为开头的连续句子不是很多，所以是保持着思路修改的，但看来我还是没理解到精髓

2021-04-16 13:03 UTC, ikexing-cn commented on docs/plots/plot.zh_cn.md
> +真是疯狂的真实，真实的疯狂。我自言自语道。
那这边暂时没有问题，保持原意。

2021-04-16 13:05 UTC, ikexing-cn commented on docs/plots/plot.zh_cn.md
> +对我来说也曾那么的真实，但现在我只感到它们的陌生和不定否决的荒诞。
但实际上苟佬你表达的是陌生和荒诞。
是的，我就是理解为记忆在计算机的存储性，东西真实与否的那种缥缈感。
所以我改的是「也曾」 更能表达不确定性质，隐约的感觉，至于荒诞之前的补词是我单纯的觉得既然是处于相信真假的悖论感，改为不可确定真假的感，这是我的感觉。

2021-04-16 13:06 UTC, ikexing-cn commented on docs/plots/plot.zh_cn.md
事实上外延是个逻辑词汇，表达的更多是以形容前词，如果你想表达概念感而非修饰，我觉得可以考虑更改词汇表达

2021-04-16 13:08 UTC, ikexing-cn commented on docs/plots/plot.zh_cn.md
实际上我更想的感觉是那种，
前期是在记忆的怀疑和相信中摸索，
主角的意识也是在模糊的感受中慢慢的觉醒，形成自然而然的感觉。
所以我考虑的时候并没有想过最开始的对抗，而是潜消默化的自然感，而所谓的对抗我感觉应该是在游戏中慢慢的与其对立来呈现应该是会更好。

2021-04-16 13:11 UTC, RisingInIris2017 commented on docs/plots/plot.zh_cn.md
这个需要我们追溯到HDS的基本设定，@GBLodb

2021-04-16 13:20 UTC, RisingInIris2017 commented on docs/plots/plot.zh_cn.md
“概念”“内涵”“外延”这三个都是逻辑学词汇。
“概念的内涵和外延”这个说法，从这三个词的逻辑学定义上说，应当是正确的。
“概念”既有“内涵”，又有“外延”，内涵和外延是“概念”的两个不同的属性。
这样说应该没有问题。

2021-04-16 13:22 UTC, GBLodb commented on docs/plots/plot.zh_cn.md
记忆和意识是两回事，此处的"对抗"所代表的抵触的情感并不是主角的意识在与超维计算机对自己记忆的修改的行做对抗，而是自然情况下当人一大部分记忆被消除的情况大脑试图回忆和连接原有的记忆时，必然会有疑惑和懊恼的情绪，甚至产生头疼等生理反应（参考Men In Black记忆消除笔）。所以此处的"但"是主角的更深层精神活动，不会在自言自语中被表达出来，综上所述，推荐保留“但”。

2021-04-16 13:23 UTC, GBLodb commented on docs/plots/plot.zh_cn.md
建议"我突然怀疑起我周围的世界来，再一次往自己的左胳膊上狠掐了一下。"延续上文的韵调

2021-04-16 13:23 UTC, RisingInIris2017 commented on docs/plots/plot.zh_cn.md
> +对我来说也曾那么的真实，但现在我只感到它们的陌生和不定否决的荒诞。
“曾经那么真实”，说明主角真的知道自己的记忆被删除了，他毫不怀疑。
这一点你也提到了，“也曾”更能表达不确定性，如果直接“曾经”，那就是主角确定自己的记忆被删除这件事。
这一点我认为也要追溯到咖喱的原始设定，@GBLodb

2021-04-16 13:25 UTC, GBLodb commented on docs/plots/plot.zh_cn.md
递进或保持与上文一致二选一，个人偏向后者，更能体现主角目前的不清醒，而不是追求交融度

2021-04-16 13:26 UTC, RisingInIris2017 commented on docs/plots/plot.zh_cn.md
至少现在这一版省略主语的句子我认为不妥。
科星佬可以考虑一个更好的写法。

2021-04-16 13:26 UTC, ikexing-cn commented on docs/plots/plot.zh_cn.md
是刚才去学术查证了一番，这一块的误差理解暂无异议，可以保持原样。
我最初的思考，内涵为总和，外延则对象，事实上和实际思考有于偏差。
所以这一块可保持原样。

2021-04-16 13:26 UTC, GBLodb commented on docs/plots/plot.zh_cn.md
没太理解原文具体想要表达的是什么

2021-04-16 13:28 UTC, GBLodb commented on docs/plots/plot.zh_cn.md
> +对我来说也曾那么的真实，但现在我只感到它们的陌生和不定否决的荒诞。
不定否决和荒诞略显语义重复，且额外的补词使整体句子显得头轻脚重了

2021-04-16 13:29 UTC, GBLodb commented on docs/plots/plot.zh_cn.md
建议保留原句“今天中午吃点啥？”

2021-04-16 13:30 UTC, ikexing-cn commented on docs/plots/plot.zh_cn.md
事实上以思考考虑，你在一篇文章中过渡不自然感会适得其反，我更偏向于后者的对于剧情发散思维的代入思考，表达的不清醒这边其实是有误差值，夜晚，疼痛清醒，二次疼痛应该是得知清醒而确认，所以这块我觉得应该是保持前者更为妥当。

2021-04-16 13:30 UTC, ikexing-cn commented on docs/plots/plot.zh_cn.md
那暂无意见的话，我推荐保留咖喱佬的提议，这个思考方向整体是对的

2021-04-16 13:31 UTC, GBLodb commented on docs/plots/plot.zh_cn.md
> +真是疯狂的真实，真实的疯狂。我自言自语道。
reality在此处当名词讲，所以"得"，"的"两者皆可，但选择"的"视觉上更加流畅，建议修改为"真实的疯狂"

2021-04-16 13:32 UTC, ikexing-cn commented on docs/plots/plot.zh_cn.md
依靠咖喱佬原始设定，这块保留「但」这个词汇作修饰

2021-04-16 13:34 UTC, GBLodb commented on docs/plots/plot.zh_cn.md
> +对我来说也曾那么的真实，但现在我只感到它们的陌生和不定否决的荒诞。
追加：主角确实是迟疑的，详见line25我的comment

2021-04-16 13:34 UTC, RisingInIris2017 commented on docs/plots/plot.zh_cn.md
这一行和第17行文字上完全一致，写主角感受到自己掐自己的疼痛感。但是你会注意到，主角掐自己的前提条件变化了。
17行掐自己是因为主角刚刚睁眼醒来，想确认一下自己是不是还在睡梦当中。
这一行又掐自己，是因为主角在自己已经清醒的状况下，开始怀疑自己所见的世界是否真实。
所以在这里，文字上完全一致不会引起信息的混乱，读者只要连贯地读下来，不会由于这两句话的字面一样而引起混淆。
这是其一。

故意制造字面上的完全一致，就是为了使读者回忆起上一次主角掐自己的桥段，就是为了让读者产生怀疑。
主角到底是不是清醒的？
而这正是主角正在做的事情，主角也在怀疑自己是不是清醒的。
这不就达到了我们需要的“读者代入”嘛。
这是其二。

最后，在序章中主角是否真的完全清醒，其实也是一个和世界观设定有关的问题。
但是我基于上述第二条的考虑，有意按照我自己的理解来写。
也就是“主角是清醒的，只是他身处的这个世界不真实”。
我的这种理解应当是和世界观设定相契合的。如果不是这样，那我们就需要对此进行修改。

2021-04-16 13:35 UTC, ikexing-cn commented on docs/plots/plot.zh_cn.md
> +对我来说也曾那么的真实，但现在我只感到它们的陌生和不定否决的荒诞。
那这块部分前者无异议，后改为
_但现在我只感到它们的陌生**与**荒诞。_

相对而言我不是很倾向于 「和」 这个字眼 对于意境的表达感其余词汇会更好

2021-04-16 13:36 UTC, GBLodb commented on docs/plots/plot.zh_cn.md
> +对我来说也曾那么的真实，但现在我只感到它们的陌生和不定否决的荒诞。
> 那这块部分前者无异议，后改为
> 但现在我只感到它们的陌生与荒诞。

approve

2021-04-16 13:37 UTC, ikexing-cn commented on docs/plots/plot.zh_cn.md
> +真是疯狂的真实，真实的疯狂。我自言自语道。
事实上在的得到了苟佬的思路后，我感觉语义不应该纯粹以视觉感为主，我更偏向于「得」的修饰让整体行文显得更有韵味。

2021-04-16 13:41 UTC, ikexing-cn commented on docs/plots/plot.zh_cn.md
居然咖喱佬和苟佬的思路是一致的，那就保留为与上方一致。

2021-04-16 13:48 UTC, RisingInIris2017 approved these changes

2021-04-16 13:49 UTC, merged

2021-05-18 16:32 UTC, GBLodb approved these changes
just found that I didn't mark myself as reviewed for this so whatever